# .github/workflows/release-nightly.yml
name: Lucia Rust Test Suite - Nightly

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '**.md'
      - 'LICENSE'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '**.md'
      - 'LICENSE'

env:
  CARGO_TERM_COLOR: always

jobs:
  nightly-build-check:
    name: Nightly Build Check (All OS)
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust (nightly)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-nightly-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-nightly-
            ${{ runner.os }}-cargo-

      - name: Install system dependencies (Unix)
        if: runner.os != 'Windows'
        run: |
          sudo apt-get update || true
          sudo apt-get install -y make || true
          brew install make || true

      - name: Install system dependencies (Windows)
        if: runner.os == 'Windows'
        run: choco install make --no-progress

      - name: Build project (release)
        run: make release

      - name: Activate build environment
        run: make activate

      - name: Upload release artifacts
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: lucia-release
          path: target/release

  nightly-build-check-arch:
    name: Nightly Build Check (Arch Linux)
    runs-on: ubuntu-latest
    container: archlinux:base-devel

    steps:
      - name: Install tools
        run: pacman -Sy --noconfirm git make rustup

      - name: Set Rust nightly
        run: rustup default nightly

      - uses: actions/checkout@v4

      - name: Restore Cargo cache
        uses: actions/cache@v3
        with:
          path: |
            /root/.cargo/registry
            /root/.cargo/git
            target
          key: arch-cargo-nightly-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            arch-cargo-nightly-
            arch-cargo-

      - name: Build project (release)
        run: make release

      - name: Activate build environment
        run: make activate

  nightly-test-suite:
    name: Nightly Test Suite (Ubuntu)
    runs-on: ubuntu-latest
    needs: nightly-build-check

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust (nightly)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-nightly-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-nightly-
            ${{ runner.os }}-cargo-

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          name: lucia-release
          path: target/release

      - name: Activate build environment
        run: make activate

      - name: Build test binaries
        run: make build-test

      - name: Run test suite
        run: make test

      - name: Run benchmarks
        run: make benchmark
