# run-tests.yml
name: Lucia Rust Test Suite

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Build lucia
        run: make release

      - name: Build tests
        run: make build-test

      - name: Run tests
        run: make test
